version: "3"
services:
  trackflix:
    container_name: trackflix
    build: .
    image: trackflix:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: trackflixDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - trackflix
    depends_on:
      - trackflixDB

  trackflixDB:
    container_name: trackflixDB
    platform: linux/amd64
    image: postgres:15.5
    env_file: .env
    restart: unless-stopped
    volumes:
      - trackflix-data:/var/lib/postgresql/data
      #- ./data:/var/lib/postgresql/data # if you want to use a bind folder
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    networks:
      - trackflix

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  trackflix-data:

networks:
  trackflix:
    name: Trackflix
    driver: bridge
