/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import documentation from "@strapi/plugin-documentation/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import cloudfrontMetrics from "../../src/plugins/cloudfront-metrics/strapi-admin";
import customSelects from "../../src/plugins/custom-selects/strapi-admin";
import docusaurus from "../../src/plugins/docusaurus/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.ts";

renderAdmin(document.getElementById("strapi"), {
  customisations,
  plugins: {
    documentation: documentation,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "cloudfront-metrics": cloudfrontMetrics,
    "custom-selects": customSelects,
    docusaurus: docusaurus,
  },
});
