name: CI/CD Pipeline
on:
  push:
    branches: [ staging ]

jobs:
  test: # we need to make a console log to see if the job is running
    runs-on: ubuntu-latest
    steps:
      - name: Console log
        run: echo "The job is running"
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/dist
            git pull origin staging
            yarn
            yarn build
            sudo pm2 restart all
